In [11]:
import pandas as pd
import datetime

In [12]:
%pwd
%cd day4

[Errno 2] No such file or directory: 'day4'
/Users/ambell/Documents/AoC2018/day4

In [13]:
# puzzle input
inputFile = open("input.txt", 'r')
inputValues = [x.strip() for x in inputFile.readlines()]  # read lines to list

# example values
exampleValues = ["[1518-11-01 00:05] falls asleep",
                 "[1518-11-01 00:25] wakes up", "[1518-11-01 00:30] falls asleep", "[1518-11-01 00:55] wakes up",
                 "[1518-11-01 23:58] Guard #99 begins shift", "[1518-11-02 00:40] falls asleep",
                 "[1518-11-02 00:50] wakes up", "[1518-11-03 00:05] Guard #10 begins shift",
                 "[1518-11-03 00:24] falls asleep", "[1518-11-03 00:29] wakes up",
                 "[1518-11-04 00:02] Guard #99 begins shift", "[1518-11-04 00:36] falls asleep",
                 "[1518-11-04 00:46] wakes up", "[1518-11-05 00:03] Guard #99 begins shift",
                 "[1518-11-05 00:45] falls asleep", "[1518-11-05 00:55] wakes up", "[1518-11-01 00:00] Guard #10 begins shift", ]

# parse inputs in
def parseInputs(line):
    ts = datetime.datetime.strptime(line[1:17], "%Y-%m-%d %H:%M")
    id = None
    if "Guard" in line:
        lineType = "id"
        id = int(line.split(" ")[3].replace("#", ""))
    if "wakes" in line:
        lineType = "wakeup"
    if "asleep" in line:
        lineType = "asleep"
    return ts, lineType, id

In [14]:
df = pd.DataFrame(exampleValues, columns=["instruction"])

df["timestamp"] = df["instruction"].apply(lambda row: datetime.datetime.strptime(row[1:17], "%Y-%m-%d %H:%M"))
df["lineType"] = df["instruction"].apply(lambda row: parseInputs(row)[1])
df["id"] = df["instruction"].apply(lambda row: parseInputs(row)[2])

# sort data frame by timestamp
df = df.sort_values('timestamp')

# forward fill id values
df["id"] = df["id"].fillna(method='ffill')
print(df)

                                  instruction            timestamp lineType  \
16  [1518-11-01 00:00] Guard #10 begins shift  1518-11-01 00:00:00       id
0             [1518-11-01 00:05] falls asleep  1518-11-01 00:05:00   asleep
1                 [1518-11-01 00:25] wakes up  1518-11-01 00:25:00   wakeup
2             [1518-11-01 00:30] falls asleep  1518-11-01 00:30:00   asleep
3                 [1518-11-01 00:55] wakes up  1518-11-01 00:55:00   wakeup
4   [1518-11-01 23:58] Guard #99 begins shift  1518-11-01 23:58:00       id
5             [1518-11-02 00:40] falls asleep  1518-11-02 00:40:00   asleep
6                 [1518-11-02 00:50] wakes up  1518-11-02 00:50:00   wakeup
7   [1518-11-03 00:05] Guard #10 begins shift  1518-11-03 00:05:00       id
8             [1518-11-03 00:24] falls asleep  1518-11-03 00:24:00   asleep
9                 [1518-11-03 00:29] wakes up  1518-11-03 00:29:00   wakeup
10  [1518-11-04 00:02] Guard #99 begins shift  1518-11-04 00:02:00       id
11            [1518-11-04 00:36] falls asleep  1518-11-04 00:36:00   asleep
12                [1518-11-04 00:46] wakes up  1518-11-04 00:46:00   wakeup
13  [1518-11-05 00:03] Guard #99 begins shift  1518-11-05 00:03:00       id
14            [1518-11-05 00:45] falls asleep  1518-11-05 00:45:00   asleep
15                [1518-11-05 00:55] wakes up  1518-11-05 00:55:00   wakeup

      id
16  10.0
0   10.0
1   10.0
2   10.0
3   10.0
4   99.0
5   99.0
6   99.0
7   10.0
8   10.0
9   10.0
10  99.0
11  99.0
12  99.0
13  99.0
14  99.0
15  99.0

In [15]:
# time sleep
df["priorTimestamp"] = df['timestamp'].shift()
df

,instruction,timestamp,lineType,id,priorTimestamp
16,[1518-11-01 00:00] Guard #10 begins shift,1518-11-01 00:00:00,id,10.0,NaN
0,[1518-11-01 00:05] falls asleep,1518-11-01 00:05:00,asleep,10.0,1518-11-01 00:00:00
1,[1518-11-01 00:25] wakes up,1518-11-01 00:25:00,wakeup,10.0,1518-11-01 00:05:00
2,[1518-11-01 00:30] falls asleep,1518-11-01 00:30:00,asleep,10.0,1518-11-01 00:25:00
3,[1518-11-01 00:55] wakes up,1518-11-01 00:55:00,wakeup,10.0,1518-11-01 00:30:00
4,[1518-11-01 23:58] Guard #99 begins shift,1518-11-01 23:58:00,id,99.0,1518-11-01 00:55:00
5,[1518-11-02 00:40] falls asleep,1518-11-02 00:40:00,asleep,99.0,1518-11-01 23:58:00
6,[1518-11-02 00:50] wakes up,1518-11-02 00:50:00,wakeup,99.0,1518-11-02 00:40:00
7,[1518-11-03 00:05] Guard #10 begins shift,1518-11-03 00:05:00,id,10.0,1518-11-02 00:50:00
8,[1518-11-03 00:24] falls asleep,1518-11-03 00:24:00,asleep,10.0,1518-11-03 00:05:00
9,[1518-11-03 00:29] wakes up,1518-11-03 00:29:00,wakeup,10.0,1518-11-03 00:24:00
10,[1518-11-04 00:02] Guard #99 begins shift,1518-11-04 00:02:00,id,99.0,1518-11-03 00:29:00
11,[1518-11-04 00:36] falls asleep,1518-11-04 00:36:00,asleep,99.0,1518-11-04 00:02:00
12,[1518-11-04 00:46] wakes up,1518-11-04 00:46:00,wakeup,99.0,1518-11-04 00:36:00
13,[1518-11-05 00:03] Guard #99 begins shift,1518-11-05 00:03:00,id,99.0,1518-11-04 00:46:00
14,[1518-11-05 00:45] falls asleep,1518-11-05 00:45:00,asleep,99.0,1518-11-05 00:03:00
15,[1518-11-05 00:55] wakes up,1518-11-05 00:55:00,wakeup,99.0,1518-11-05 00:45:00

In [16]:
# elapsed time
df["elapsed"] = df['timestamp'] - df['priorTimestamp']
df

,instruction,timestamp,lineType,id,priorTimestamp,elapsed
16,[1518-11-01 00:00] Guard #10 begins shift,1518-11-01 00:00:00,id,10.0,NaN,NaT
0,[1518-11-01 00:05] falls asleep,1518-11-01 00:05:00,asleep,10.0,1518-11-01 00:00:00,00:05:00
1,[1518-11-01 00:25] wakes up,1518-11-01 00:25:00,wakeup,10.0,1518-11-01 00:05:00,00:20:00
2,[1518-11-01 00:30] falls asleep,1518-11-01 00:30:00,asleep,10.0,1518-11-01 00:25:00,00:05:00
3,[1518-11-01 00:55] wakes up,1518-11-01 00:55:00,wakeup,10.0,1518-11-01 00:30:00,00:25:00
4,[1518-11-01 23:58] Guard #99 begins shift,1518-11-01 23:58:00,id,99.0,1518-11-01 00:55:00,23:03:00
5,[1518-11-02 00:40] falls asleep,1518-11-02 00:40:00,asleep,99.0,1518-11-01 23:58:00,00:42:00
6,[1518-11-02 00:50] wakes up,1518-11-02 00:50:00,wakeup,99.0,1518-11-02 00:40:00,00:10:00
7,[1518-11-03 00:05] Guard #10 begins shift,1518-11-03 00:05:00,id,10.0,1518-11-02 00:50:00,23:15:00
8,[1518-11-03 00:24] falls asleep,1518-11-03 00:24:00,asleep,10.0,1518-11-03 00:05:00,00:19:00
9,[1518-11-03 00:29] wakes up,1518-11-03 00:29:00,wakeup,10.0,1518-11-03 00:24:00,00:05:00
10,[1518-11-04 00:02] Guard #99 begins shift,1518-11-04 00:02:00,id,99.0,1518-11-03 00:29:00,23:33:00
11,[1518-11-04 00:36] falls asleep,1518-11-04 00:36:00,asleep,99.0,1518-11-04 00:02:00,00:34:00
12,[1518-11-04 00:46] wakes up,1518-11-04 00:46:00,wakeup,99.0,1518-11-04 00:36:00,00:10:00
13,[1518-11-05 00:03] Guard #99 begins shift,1518-11-05 00:03:00,id,99.0,1518-11-04 00:46:00,23:17:00
14,[1518-11-05 00:45] falls asleep,1518-11-05 00:45:00,asleep,99.0,1518-11-05 00:03:00,00:42:00
15,[1518-11-05 00:55] wakes up,1518-11-05 00:55:00,wakeup,99.0,1518-11-05 00:45:00,00:10:00

In [9]:
# total time alsleep by guard
sleepDF = df.loc[df['lineType'] == 'wakeup']
# grab the totals for the wakeup 
sleepTotals = sleepDF.groupby('id').sum()

sleepTotals.sort_values('elapsed')
sleepGuardID = 1021
print(f"Guard {sleepGuardID} sleeps the most")

Guard 1021 sleeps the most

In [25]:
# subset the data frame to just the guards recs
guardDF = df.loc[df['id']== 10]
guardDF["minute"] = guardDF["timestamp"].apply(lambda row: row.minute)

guardDF

/Users/ambell/anaconda3/envs/excelparser/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,instruction,timestamp,lineType,id,priorTimestamp,elapsed,minute
16,[1518-11-01 00:00] Guard #10 begins shift,1518-11-01 00:00:00,id,10.0,NaN,NaT,0
0,[1518-11-01 00:05] falls asleep,1518-11-01 00:05:00,asleep,10.0,1518-11-01 00:00:00,00:05:00,5
1,[1518-11-01 00:25] wakes up,1518-11-01 00:25:00,wakeup,10.0,1518-11-01 00:05:00,00:20:00,25
2,[1518-11-01 00:30] falls asleep,1518-11-01 00:30:00,asleep,10.0,1518-11-01 00:25:00,00:05:00,30
3,[1518-11-01 00:55] wakes up,1518-11-01 00:55:00,wakeup,10.0,1518-11-01 00:30:00,00:25:00,55
7,[1518-11-03 00:05] Guard #10 begins shift,1518-11-03 00:05:00,id,10.0,1518-11-02 00:50:00,23:15:00,5
8,[1518-11-03 00:24] falls asleep,1518-11-03 00:24:00,asleep,10.0,1518-11-03 00:05:00,00:19:00,24
9,[1518-11-03 00:29] wakes up,1518-11-03 00:29:00,wakeup,10.0,1518-11-03 00:24:00,00:05:00,29

In [58]:
def minuteBins(ts1, ts2, delta):
    print(ts1, ts2)
    tsBins = []
    
    if ts1 is not None and ts2 is not None:
        current = ts1
        while current < ts2:
            current += datetime.timedelta(minutes=1)
            tsBins.append(current.minute)
    return tsBins
    
a = minuteBins(datetime.datetime.strptime("1518-11-01 00:00", "%Y-%m-%d %H:%M"), datetime.datetime.strptime("1518-11-01 00:05", "%Y-%m-%d %H:%M"), 1)

1518-11-01 00:00:00 1518-11-01 00:05:00

In [59]:
# subset the data frame to just the guards recs
guardDF = df.loc[df['id']== 10]
guardDF["minute"] = guardDF["timestamp"].apply(lambda row: row.minute)

guardDF["minutebins"] = guardDF[['priorTimestamp', 'timestamp']].apply(lambda row: minuteBins(row[0], row[1], 1))
guardDF

1518-11-01 00:05:00 1518-11-01 00:00:00
1518-11-01 00:25:00 1518-11-01 00:05:00

/Users/ambell/anaconda3/envs/excelparser/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/ambell/anaconda3/envs/excelparser/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

,instruction,timestamp,lineType,id,priorTimestamp,elapsed,minute,minutebins
16,[1518-11-01 00:00] Guard #10 begins shift,1518-11-01 00:00:00,id,10.0,NaN,NaT,0,NaN
0,[1518-11-01 00:05] falls asleep,1518-11-01 00:05:00,asleep,10.0,1518-11-01 00:00:00,00:05:00,5,NaN
1,[1518-11-01 00:25] wakes up,1518-11-01 00:25:00,wakeup,10.0,1518-11-01 00:05:00,00:20:00,25,NaN
2,[1518-11-01 00:30] falls asleep,1518-11-01 00:30:00,asleep,10.0,1518-11-01 00:25:00,00:05:00,30,NaN
3,[1518-11-01 00:55] wakes up,1518-11-01 00:55:00,wakeup,10.0,1518-11-01 00:30:00,00:25:00,55,NaN
7,[1518-11-03 00:05] Guard #10 begins shift,1518-11-03 00:05:00,id,10.0,1518-11-02 00:50:00,23:15:00,5,NaN
8,[1518-11-03 00:24] falls asleep,1518-11-03 00:24:00,asleep,10.0,1518-11-03 00:05:00,00:19:00,24,NaN
9,[1518-11-03 00:29] wakes up,1518-11-03 00:29:00,wakeup,10.0,1518-11-03 00:24:00,00:05:00,29,NaN